name: Demo Container action

on:
  workflow_dispatch:

jobs:
  container_action:
    runs-on: ubuntu-latest
    steps:
      - uses: lfraile-git-school/container-action@main
        with:
          myInput: "Luis Fraile"
