name: Demo Composite action

on:
  workflow_dispatch:    
  push:
    paths: .github/workflows/demo-composite-action.yml

jobs:
  container_action:
    runs-on: ubuntu-latest
    steps:
      - uses: lfraileorg/composite-action@v1
        with:
          who-to-greet: "Luis Fraile"
