name: Demo Container action

on:
  push:
    paths: .github/workflows/demo-container-action.yml

jobs:
  container_action:
    runs-on: ubuntu-latest
    steps:
      - uses: wulfland/hello-world-docker-action@main
        id: hello-action
        with:
          myInput: "Luis Fraile"
      - name: Output time
        run: echo "The time is ${{ steps.hello-action.outputs.time }}"
